name: CI Build

on:
  workflow_dispatch:
  push:    
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET (global.json)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build
        env:
          DOTNET_NUGET_SIGNATURE_VERIFICATION: false
        run: dotnet build hearts.sln
      - name: Test
        run: |
            dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover \
            test/Hearts.Api.UnitTests/Hearts.Api.UnitTests.csproj
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ngruson/hearts
